from glob import glob

auto_libs = ''

# Detect the system's endianness
from sys import byteorder
if byteorder == 'big':
	endian = '_NXT_BIG_ENDIAN'
else:
	endian = '_NXT_LITTLE_ENDIAN'

BuildEnv = Environment(CCFLAGS=['-Wall'
                                ,'-D' + endian])

if auto_libs:
	BuildEnv.ParseConfig('pkg-config --cflags --libs ' + auto_libs)

Default(BuildEnv.Library('c_nxt',
			 [x for x in glob('*.c')
			  if not x.startswith('main')],
			 LIBS=['bluetooth']))